// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	   int limit = Integer.parseInt("" + args[0]);
	   double ran1 = (Math.random());
	   int low = 0;
	   int high = 0;
	   for (int i = 0; i < limit; i++) {
			ran1 = (Math.random());
			if (ran1 > 0.5 ) {
				high++;

			}
			else {
				low++;
			}
			System.out.println(ran1);
		}
		System.out.println("> 0.5: " + high + " times");
		System.out.println("<= 0.5: " + low + " times");
		if (low!=0){
			double ratio = (double)high/low;
			System.out.println("Ratio: " + ratio);
		}
	}
}
